### ISSUE TITLE
type error: undefined table

### ISSUE THREAD

**Issue by shriharip** [joist-orm/joist-sample#2]
1. cloned the repo
    2. yarn install
    3. changed env to postgres I have hosted
    4. run pg-migrate
          It created the tables in the postgres
    5. run joist-codegen

````
TypeError: Cannot read properties of undefined (reading 'table')
    at get referencedTable [as referencedTable] (/Users/hari/joist-sample/node_modules/pg-structure/dist/pg-structure/constraint/foreign-key.js:29:27)
    at /Users/hari/joist-sample/node_modules/pg-structure/dist/main.js:287:28
    at Array.forEach (<anonymous>)
    at addConstraints (/Users/hari/joist-sample/node_modules/pg-structure/dist/main.js:261:10)
    at addObjects (/Users/hari/joist-sample/node_modules/pg-structure/dist/main.js:337:5)
    at pgStructure (/Users/hari/joist-sample/node_modules/pg-structure/dist/main.js:378:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadSchemaMetadata (/Users/hari/joist-sample/node_modules/joist-codegen/build/index.js:83:16)
    at async main (/Users/hari/joist-sample/node_modules/joist-codegen/build/index.js:29:24)
   
````

**Comment by stephenh** [comment]
Hi @shriharip ! Thanks for trying Joist out...

This error is happening in `pg-structure`, the library we use to scan the metadata from postgres, around this line:

```
class ForeignKey extends constraint_1.default {
    /** @ignore */
    constructor(args) {
        super(args);
        this.onUpdate = args.onUpdate;
        this.onDelete = args.onDelete;
        this.matchType = args.matchType;
        this.index = args.index;
        this.columns = indexable_array_1.default.throwingFrom(args.columns, "name");
        this.table = args.table;
        this.mandatoryParent = this.columns.every((column) => column.notNull);
    }
    /**
     * This is [[Table]] instance this {@link ForeignKey foreign key} refers to.
     */
    get referencedTable() {
        // it's not possible to have an foreign key on a materialized view, so
        // `index.table` will always be defined
        return this.index.table;
    }
```

On that `this.index.table` line...

Which is weird, and not something I've seen before. It looks like there is a constraint without an index. I'm going to file a bug with pg-structure and see what they think:

https://github.com/ozum/pg-structure/issues/92

@shriharip if you wanted to help debug this, I think if you ran:

```sql
SELECT
  c.conrelid AS "tableOid",
  c.conindid AS "indexOid",
  c.contypid AS "typeOid",
  c.contype AS "kind", -- c: check, f: foreign key, p: primary key, u: unique, t: constraint trigger, x: exclusion constraint
  c.conname AS "name",
  c.conkey::int[] AS "constrainedColumnPositions",
  c.confkey::int[] AS "referencedColumnPositions",
  c.confupdtype AS "onUpdate",
  c.confdeltype AS "onDelete",
  c.confmatchtype AS "matchType",
  c.condeferrable AS "isDeferrable",
  c.condeferred AS "isDeferred",
  pg_get_constraintdef(c.oid) AS "checkConstraintExpression",
  pg_catalog.obj_description(c.oid, 'pg_constraint') AS "comment"
FROM
  pg_constraint c
ORDER BY
  c.conindid = 0, c.connamespace, LOWER(c.conname)
```

In your database, that will put the "constraints without an index" i.e. where `indexOid` is 0 up-at-the-top, and maybe that will help us see what is unique about your application's foreign key constraints.

I.e. it sounds like there is a column with a FK constraint, but without an index?

**Comment by shriharip** [comment]
@stephenh 

Thanks so much for helping me with this. For more context, my Db is a supabase postgres instance.

**Comment by stephenh** [comment]
Hi @shriharip , thanks for working with me on this!

My current guess is that it looks like you have a lot of different schemas; like instead of everything being in a single `public` schema, you've got a few different schemas like `auth`, `storage`, and `pgsodium`.

And it seems like pg-structure has found a foreign key, but can't find the constraint ... perhaps b/c it's in a different schema? I don't even know how that'd happen.

Can you try this SQL query:

```sql
WITH indexes AS (
SELECT
  indexrelid AS "oid",
  ix.indrelid AS "tableOid",
  index_class.relname AS "name",
  ix.indisunique AS "isUnique",
  ix.indisprimary AS "isPrimaryKey",
  ix.indisexclusion AS "isExclusion",
  indkey::int[] AS "columnPositions",
  COALESCE(regexp_split_to_array(pg_get_expr(indexprs, ix.indrelid), ', '), '{}'::text[]) AS "indexExpressions",
  pg_get_expr(indpred, ix.indrelid) AS "partialIndexExpression",
  pg_catalog.obj_description(indexrelid, 'pg_index') AS "comment"
FROM
  pg_index ix
  INNER JOIN pg_class index_class ON index_class.oid = ix.indexrelid --AND index_class.relkind = 'i') -- Indexes only from pg_class, i: indexes
ORDER BY
  ix.indrelid,
  LOWER(index_class.relname)
)
SELECT
  c.conrelid AS "tableOid",
  c.conindid AS "indexOid",
  c.contypid AS "typeOid",
  c.contype AS "kind", -- c: check, f: foreign key, p: primary key, u: unique, t: constraint trigger, x: exclusion constraint
  c.conname AS "name",
  c.conkey::int[] AS "constrainedColumnPositions",
  c.confkey::int[] AS "referencedColumnPositions",
  c.confupdtype AS "onUpdate",
  c.confdeltype AS "onDelete",
  c.confmatchtype AS "matchType",
  c.condeferrable AS "isDeferrable",
  c.condeferred AS "isDeferred",
  pg_get_constraintdef(c.oid) AS "checkConstraintExpression",
  pg_catalog.obj_description(c.oid, 'pg_constraint') AS "comment"
FROM
  pg_constraint c
  LEFT JOIN indexes i ON c.conindid = i.oid
  WHERE i.oid IS NULL
ORDER BY
  c.connamespace,
  LOWER(c.conname)
```

The `WHERE i.oid IS NULL` will hopefully let us narrow down what FK constraint can't find index index. 

Hopefully we can at least get `pg-structure` to successfully pull back the data, but otherwise Joist might need some sort to support multiple schemas :thinking: . Do you generally have a unified domain model, with some tables in `auth`, some tables in `storage`, and you'd like to have them all pulled into a single Joist domain model?

**Comment by shriharip** [comment]
oh wow, you might be right @stephenh 
I do have different schemas, auth, storage and different tables in them. However, I have not included then in the joist domain model. 
At least in the case of `supabase`, it just creates a postgres table and fills it with this tables in  `auth`, `storage` etc. and I just put in my own tables `author`, `books` in joist.  

I did run your query and the results are below 

````
| tableOid | indexOid | typeOid | kind | name                                    | constrainedColumnPositions | referencedColumnPositions | onUpdate | onDelete | matchType | isDeferrable | isDeferred | checkConstraintExpression                                                                                                                                                                                              | comment |
| -------- | -------- | ------- | ---- | --------------------------------------- | -------------------------- | ------------------------- | -------- | -------- | --------- | ------------ | ---------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------- |
| 0        | 0        | 13169   | c    | cardinal_number_domain_check            |                            |                           |          |          |           | false        | false      | CHECK ((VALUE >= 0))                                                                                                                                                                                                   |         |
| 0        | 0        | 13182   | c    | yes_or_no_check                         |                            |                           |          |          |           | false        | false      | CHECK (((VALUE)::text = ANY ((ARRAY['YES'::character varying, 'NO'::character varying])::text[])))                                                                                                                     |         |
| 28729    | 0        | 0       | c    | domain not empty                        | 3                          |                           |          |          |           | false        | false      | CHECK ((char_length(domain) > 0))                                                                                                                                                                                      |         |
| 28744    | 0        | 0       | c    | entity_id not empty                     | 3                          |                           |          |          |           | false        | false      | CHECK ((char_length(entity_id) > 0))                                                                                                                                                                                   |         |
| 28744    | 0        | 0       | c    | metadata_url not empty                  | 5                          |                           |          |          |           | false        | false      | CHECK (((metadata_url = NULL::text) OR (char_length(metadata_url) > 0)))                                                                                                                                               |         |
| 28744    | 0        | 0       | c    | metadata_xml not empty                  | 4                          |                           |          |          |           | false        | false      | CHECK ((char_length(metadata_xml) > 0))                                                                                                                                                                                |         |
| 28865    | 0        | 0       | c    | one_time_tokens_token_hash_check        | 4                          |                           |          |          |           | false        | false      | CHECK ((char_length(token_hash) > 0))                                                                                                                                                                                  |         |
| 28762    | 0        | 0       | c    | request_id not empty                    | 3                          |                           |          |          |           | false        | false      | CHECK ((char_length(request_id) > 0))                                                                                                                                                                                  |         |
| 28720    | 0        | 0       | c    | resource_id not empty                   | 2                          |                           |          |          |           | false        | false      | CHECK (((resource_id = NULL::text) OR (char_length(resource_id) > 0)))                                                                                                                                                 |         |
| 16489    | 0        | 0       | c    | users_email_change_confirm_status_check | 29                         |                           |          |          |           | false        | false      | CHECK (((email_change_confirm_status >= 0) AND (email_change_confirm_status <= 2)))                                                                                                                                    |         |
| 16790    | 0        | 0       | c    | key_key_context_check                   | 7                          |                           |          |          |           | false        | false      | CHECK ((length(key_context) = 8))                                                                                                                                                                                      |         |
| 16790    | 0        | 0       | c    | pgsodium_raw                            | 10,6,7,12                  |                           |          |          |           | false        | false      | CHECK (
CASE
    WHEN (raw_key IS NOT NULL) THEN ((key_id IS NULL) AND (key_context IS NULL) AND (parent_key IS NOT NULL))
    ELSE ((key_id IS NOT NULL) AND (key_context IS NOT NULL) AND (parent_key IS NULL))
END) |         |
`````
I might sound stupid but I have zero knowledge about this and better to learn. so here goes my question - Do you think it is necessary to read the whole postgres schema and then do the code-gen or just look into the migrations and do the code-gen?

**Comment by stephenh** [comment]
> Do you think it is necessary to read the whole postgres schema

Ironically we used to only read the `public` schema, but then ran into basically this same issue when our primary tables when triggers that point to functions in the `cyanaudit` (an off-the-shelf auditing library) schema.

So we assumed "well, just pull in all the schemas!" would be a good idea, but now it seems to be causing the opposite issue here. :-/

Let me put together a PR that adds an explicit `schemas: ...` flag to the `joist-config.json` file, and than we should be able to get this working...

I'm also curious to just try supabase, maybe this weekend I'll have a chance to create an account and try it.

If it's okay, I'll just comment here when it's a good time for you to try again? Thanks!

**Comment by stephenh** [comment]
Ah, good news! I found an easy fix in pg-structure; and was able to run `yarn codegen` against my supabase project.

Hopefully the bug fix for pg-structure will be accepted/released soon, and we can pull it into Joist.

**Comment by shriharip** [comment]
Wow, cool. Will definitely check this out after the fix. Thanks again @stephenh

**Comment by stephenh** [comment]
Alright, I've pushed a "bump joist" commit to this `joist-sample` app, and it now executes successfully against my trial supabase account.

Thanks for the report @shriharip ! Let us know if you run into anything else. :-)
